# Generated by Django 4.2 on 2023-04-08 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createddesigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='images/')),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pro_status', models.BooleanField(default=False)),
                ('pro_code', models.IntegerField(default=0)),
                ('numberdesigns', models.IntegerField(default=0)),
                ('paymentvertfication', models.BooleanField(default=False)),
                ('trial_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='saveddesigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animade.createddesigns')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'design')},
            },
        ),
    ]
