# Generated by Django 4.2 on 2023-04-13 00:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animade', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createddesigns',
            new_name='CreatedDesign',
        ),
        migrations.RenameModel(
            old_name='saveddesigns',
            new_name='SavedDesign',
        ),
    ]
