# Generated by Django 4.2 on 2023-06-18 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animade', '0005_rename_createddesigns_createddesign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createddesign',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createddesign',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
